apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default-deny.yaml
  - deny-cloud-metadata.yaml
  - allow-ingress-from-traefik.yaml
  - allow-ingress-from-monitoring.yaml
