apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-world
  namespace: hello-world
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hello-world
  namespace: hello-world
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: hello-world
    namespace: hello-world
