apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hello-world
  namespace: hello-world
spec:
  interval: 5m
  url: https://github.com/lucas2kdk/hailmary-helloworld
  ref:
    branch: main
  ignore: |
    /*
    !/chart/
